drivers: power: bq27z561_fg: fix build error when qpnp-fg-gen4 enabled it will cause build error aarch64-linux-gnu-ld: drivers/power/supply/qcom/bq27z561_fg.o:/home/bruce/Xiaomi_Kernel_OpenSource/out/../drivers/power/supply/qcom/bq27z561_fg.c:2462: multiple definition of `lowsoc_highvolt_smooth'; drivers/power/supply/qcom/qpnp-fg-gen4.o:/home/bruce/Xiaomi_Kernel_OpenSource/out/../drivers/power/supply/qcom/qpnp-fg-gen4.c:7028: first defined here